name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
        env:
          MICROSOFT_ACADEMIC_API_KEY: ${{ secrets.MICROSOFT_ACADEMIC_API_KEY }}
